Bump github actions dependencies
AlmaLinux/alma-tests-cacher pull request #29
Opened 2024-02-07 15:33 UTC by maccelf

Resolves: AlmaLinux/build-system#181

2024-02-07 15:56 UTC, javihernandez approved these changes

2024-02-07 15:59 UTC, javihernandez requested changes
None of the updated workflows ran, can you please check?

2024-02-07 16:24 UTC, maccelf commented
@javihernandez That's because we don't have any changed Python files. But I can change something for test

2024-02-07 18:27 UTC, javihernandez approved these changes

2024-02-13 11:39 UTC, zklevsha approved these changes

2024-02-13 13:24 UTC, merged